# Generated by Django 3.0.8 on 2020-07-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
