# Generated by Django 3.0.8 on 2020-09-24 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='e-mail')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст обращения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback', verbose_name='Приложенное изображение')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ на отзыв')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
    ]
